import type {TimeOfDay, UserStatusState, AetherNovaMessageState} from "./types";

export const CLOCK_PATTERN = /\b([01]?\d|2[0-3]):([0-5]\d)\b/;
export const TIME_OF_DAYS: TimeOfDay[] = ["Morning", "Midday", "Afternoon", "Evening", "Night"];
export const HEADER_DIVIDER = "***";
export const NPC_MEMORY_COMMAND_PATTERN = /(?:[\[【]\s*)?npc[\s_-]*memory\s+((?:delete|remove|clearfacts|clear\s+facts|clear|set|update|add\s+fact|addfact|relation\s+event|relationship\s+event|relationship|relation|behavior\s+score|behavior|mood|show)\s*:?\s*[^\n\]】]+)(?:[\]】])?/gi;

export const DEFAULT_USER_STATUS: UserStatusState = {
  gender: "Unknown",
  apparentRace: "Human",
  clothing: {},
  weapons: [],
  importantItems: [],
};

export const DEFAULT_STATE: AetherNovaMessageState = {
    location: "Unknown Region - Current Place - Active Area",
    timeOfDay: "Morning",
    clock: "09:00",
    you: "Unknown - Human (Regular clothing; Standing; hands visible)",
    npc: "None",
    thread: "None",
    wallet: "0G ; 0S ; 0C",
    walletInitialized: false,
    npcMemory: {},
    pendingNpcDebugQuery: null,
    pendingNpcMemoryCommand: null,
    userStatus: { ...DEFAULT_USER_STATUS },
};

export const RACE_KEYWORDS = [
    "Kitsune",
    "Catkin",
    "Dragonkin",
    "Angel",
    "Demon",
    "Vampire",
    "Pixie",
    "Fey",
    "Elf",
    "Dwarf",
    "Orc",
    "Human",
];

export const THREAD_TRANSITION_CUES = [
    "arrived",
    "arrive",
    "entered",
    "enter",
    "left",
    "leave",
    "later",
    "meanwhile",
    "afterward",
    "afterwards",
    "resolved",
    "concluded",
    "finished",
    "began",
    "started",
    "agreed",
    "decided",
    "mission",
    "quest",
    "objective",
    "travel",
    "journey",
    "teleport",
    "time skip",
    "correct",
    "correction",
    "mistake",
    "non-canon",
];

export const THREAD_INFERENCE_CUES = [
    "mission",
    "quest",
    "objective",
    "task",
    "contract",
    "order",
    "orders",
    "ordered",
    "appointment",
    "meeting",
    "audience",
    "promise",
    "promises",
    "promised",
    "vow",
    "vows",
    "vowed",
    "deadline",
    "meet",
    "visit",
    "speak",
    "talk",
    "ask",
    "information",
    "info",
    "intel",
    "lead",
    "clue",
    "whereabouts",
    "location",
    "hunt",
    "hunting",
    "travel goal",
    "major obstacle",
    "unresolved conflict",
];

export const LOCATION_TRANSITION_CUES = [
    "move",
    "moves",
    "moved",
    "leads",
    "led",
    "follow",
    "follows",
    "followed",
    "travel",
    "travels",
    "traveled",
    "journey",
    "arrive",
    "arrives",
    "arrived",
    "enter",
    "enters",
    "entered",
    "leave",
    "leaves",
    "left",
    "combat",
    "battle",
    "teleport",
    "time skip",
    "scene transition",
    "meanwhile",
    "later",
    "afterward",
    "afterwards",
];

export const LOCATION_SCENE_ANCHOR_CUES = [
    "inside",
    "within",
    "interior",
    "indoors",
    "room",
    "hall",
    "chamber",
    "floor",
    "walls",
    "ceiling",
    "doorway",
    "threshold",
    "counter",
    "table",
    "booth",
    "stool",
    "bartender",
    "patron",
];

export const POSITION_CHANGE_CUES = [
    "move",
    "moves",
    "moved",
    "walk",
    "walks",
    "walked",
    "walking",
    "stand",
    "stands",
    "stood",
    "standing",
    "sit",
    "sits",
    "sat",
    "sitting",
    "seated",
    "kneel",
    "kneels",
    "kneeling",
    "lean",
    "leans",
    "turn",
    "turns",
    "step",
    "steps",
    "lie",
    "lies",
    "lying",
    "lay",
    "laid",
    "recline",
    "reclines",
    "reclining",
    "reclined",
    "sideways",
    "on side",
    "on his side",
    "on her side",
    "on their side",
    "on your side",
    "pin",
    "pins",
    "pinned",
    "pinning",
    "hold down",
    "holds down",
    "held down",
    "holding down",
    "restrain",
    "restrains",
    "restrained",
    "restraining",
    "straddle",
    "straddles",
    "straddling",
    "mount",
    "mounts",
    "mounted",
    "mounting",
    "on top of",
    "approach",
    "approaches",
    "behind",
    "beside",
    "before",
    "door",
    "table",
    "throne",
    "combat",
    "battle",
    "scene transition",
    "time skip",
    "stop",
    "stops",
    "stopped",
    "halt",
    "halts",
    "arrive",
    "arrives",
    "arrived",
    "reach",
    "reaches",
    "reached",
    "destination",
    "left of",
    "right of",
    "left side",
    "right side",
    "next to",
    "in front of",
    "across from",
    "facing",
    "steps away",
    "steps before",
    "paces away",
    "paces before",
    "berdiri",
    "duduk",
    "berlutut",
    "berbaring",
    "rebah",
    "tidur",
    "miring",
    "telentang",
    "terlentang",
    "tengkurap",
    "menahan",
    "menindih",
    "di atas",
    "di bawah",
    "di atas musuh",
    "di bawahku",
    "sebelah kiri",
    "sebelah kanan",
    "di kiri",
    "di kanan",
    "di samping",
    "di hadapan",
    "di depan",
    "di belakang",
    "langkah",
];

export const POSITION_SPATIAL_CUES = [
    "left of",
    "right of",
    "left side",
    "right side",
    "beside",
    "next to",
    "near",
    "above",
    "below",
    "beneath",
    "under",
    "over",
    "on top of",
    "over top of",
    "on his side",
    "on her side",
    "on their side",
    "on your side",
    "atop",
    "upon",
    "against",
    "beyond",
    "past",
    "around",
    "inside",
    "outside",
    "alongside",
    "before",
    "behind",
    "in front of",
    "across from",
    "facing",
    "toward",
    "towards",
    "ahead",
    "opposite",
    "between",
    "steps",
    "paces",
    "arm's length",
    "sebelah kiri",
    "sebelah kanan",
    "di kiri",
    "di kanan",
    "di samping",
    "di hadapan",
    "di depan",
    "di belakang",
    "di atas",
    "di bawah",
    "di atas musuh",
    "di bawahku",
    "miring",
    "menghadap",
    "langkah",
];

export const POSTURE_BODY_KEYWORDS = [
  "posture", "stance", "standing", "sitting", "kneeling", "leaning",
  "crouching", "lying", "lying down", "lying sideways", "lying on side", "sideways",
  "reclining", "reclined", "sprawled", "prone", "supine",
  "pinned", "pinning", "straddling", "mounted", "mounting", "restraining", "holding down",
  "berbaring", "rebah", "miring", "telentang", "terlentang", "tengkurap", "menahan", "menindih",
  "relaxed", "tense", "defensive",
  "arms crossed", "hand on hip", "hands lowered", "hands on",
  "eyes narrowed", "watching", "facing", "turning", "holding", "touching",
  "body", "shoulders", "back straight", "head tilted", "head lowered",
  "gaze", "looking", "staring", "glancing",
];

export const THREAD_WAITING_PATTERNS = [
  /\b\w+\s+(?:waiting|awaits?|awaiting)\s+(?:at|by|near|outside|in|for)\b/i,
  /\b(?:rendezvous|meeting)\s+(?:with\s+)?[A-Z][A-Za-z'._-]+\b/i,
  /\bmeet\s+(?:with\s+)?[A-Z][A-Za-z'._-]+\s+(?:at|by|near|outside|in)\b/i,
  /\b[pP]ending\s+(?:meeting|rendezvous)\b/,
  /\b[pP]romised\s+(?:meeting|rendezvous)\b/,
  /\b[A-Z][A-Za-z'._-]+\s+(?:awaiting|waiting\s+for)\s+\{\{user\}\}\b/i,
  /\b[A-Z][A-Za-z'._-]+\s+waiting\b/i,
];

export const THREAD_WAITING_RESOLUTION_PATTERNS = [
  /\b(?:reaches?|reached|arrives?\s+at|arrived\s+at|enters?\s+|entered)\b.*\b(?:waiting|finds?\s+|found)\b/i,
  /\b(?:meets?\s+|met\s+)(?:with\s+)?[A-Z][A-Za-z'._-]+\s+(?:at|by|near|outside|in)\b/i,
  /\b[A-Z][A-Za-z'._-]+\s+(?:leaves?|left|departs?|departed)\b.*\b(?:after\s+)?(?:waiting)\b/i,
  /\b(?:meeting|rendezvous)\s+(?:is\s+)?(?:cancelled|canceled|abandoned|over|done|finished)\b/i,
  /\bwait(s|ed)?\s+(?:too\s+)?long\b.*\b(?:leave|left|depart)\b/i,
];

export const CLOTHING_CHANGE_CUES = [
    "change clothes",
    "changed clothes",
    "changes clothes",
    "change into",
    "changed into",
    "changes into",
    "change outfit",
    "changed outfit",
    "changes outfit",
    "wear",
    "wears",
    "wearing",
    "wore",
    "put on",
    "puts on",
    "putting on",
    "dress in",
    "dresses in",
    "dressed in",
    "clad in",
    "dons",
    "donned",
    "donning",
    "slip into",
    "slips into",
    "slipped into",
    "wrap in",
    "wraps in",
    "wrapped in",
    "swap into",
    "swaps into",
    "swapped into",
    "new outfit",
    "new clothes",
    "remove armor",
    "removes armor",
    "removed armor",
    "new disguise",
    "changes disguise",
    "changed disguise",
    "only wearing",
    "wears only",
    "wearing only",
    "left sleeve",
    "right sleeve",
    "loose shirt",
    "loose pants",
    "baggy shirt",
    "baggy pants",
    "shirt caught",
    "pants caught",
    "sleeve caught",
    "clothes caught",
    "clothing caught",
    "baju longgar",
    "celana longgar",
    "hanya memakai",
    "tersangkut",
];

export const CLOTHING_DAMAGE_CUES = [
    "burn",
    "burns",
    "burned",
    "burnt",
    "scorch",
    "scorched",
    "tear",
    "tears",
    "torn",
    "rip",
    "rips",
    "ripped",
    "shred",
    "shredded",
    "cut",
    "cuts",
    "slashed",
    "bloody",
    "bloodied",
    "stained",
    "soaked",
    "wet",
    "muddy",
    "damaged",
    "destroyed",
    "frayed",
    "singed",
    "loose",
    "loosened",
    "baggy",
    "caught",
    "catches",
    "snag",
    "snags",
    "snagged",
    "stuck",
    "hooked",
    "tangled",
    "slipping",
    "untucked",
    "unbuttoned",
    "unfastened",
    "missing sleeve",
    "armor cracked",
    "cloak catches fire",
    "sleeve catches fire",
    "robek",
    "terbakar",
    "longgar",
    "tersangkut",
];

export const CLOTHING_REMOVAL_CUES = [
    "remove",
    "removes",
    "removed",
    "take off",
    "takes off",
    "took off",
    "strip",
    "strips",
    "stripped",
    "undress",
    "undresses",
    "undressed",
    "bare",
    "naked",
    "shirtless",
    "topless",
    "without clothes",
    "without shirt",
    "without armor",
    "without cloak",
    "remove cloak",
    "removes cloak",
    "removed cloak",
    "only pants",
    "pants only",
    "wearing only pants",
    "wears only pants",
    "only wearing pants",
    "hanya memakai celana",
];

export const CLOTHING_ADJUSTMENT_CUES = [
    "fix",
    "fixes",
    "fixed",
    "fixing",
    "adjust",
    "adjusts",
    "adjusted",
    "adjusting",
    "straighten",
    "straightens",
    "straightened",
    "straightening",
    "smooth",
    "smooths",
    "smoothed",
    "smoothing",
    "settle",
    "settles",
    "settled",
    "settling",
    "fasten",
    "fastens",
    "fastened",
    "fastening",
    "refasten",
    "refastens",
    "refastened",
    "refastening",
    "tie",
    "ties",
    "tied",
    "tying",
    "retie",
    "reties",
    "retied",
    "retying",
    "cover",
    "covers",
    "covered",
    "covering",
    "back into place",
    "into place",
];

export const CLOTHING_DAMAGE_WORDS = /\b(burned|burnt|scorched|torn|ripped|shredded|slashed|bloody|bloodied|stained|soaked|wet|muddy|damaged|destroyed|cracked|frayed|singed|loose|loosened|baggy|caught|snagged|stuck|hooked|tangled|slipping|untucked|unbuttoned|unfastened|missing|robek|terbakar|longgar|tersangkut)\b/i;
export const CLOTHING_SLOT_PATTERN = /\b(cloth|clothes|clothing|garment|garments|layer|layers|outfit|attire|garb|uniform|armor|armour|robe|robes|over-robe|under-robe|overrobe|underrobe|kimono|yukata|haori|hakama|dress|gown|nightgown|nightdress|pajama|pajamas|suit|shirt|blouse|tunic|jacket|coat|cloak|mantle|cape|hood|pants|pant|trousers|jeans|shorts|skirt|leggings|boots|shoes|sandals|gloves|mask|veil|hat|cap|helmet|apron|vest|corset|sash|belt|scarf|shawl|wrap|rags|disguise|leather|silk|linen|cotton|wool|chainmail|mail|sleeve|sleeves|collar|hem|cuff|cuffs|waistband|pantleg|pantlegs|naked|nude|unclothed|bare|baju|celana|pakaian|kemeja|lengan baju|kain)\b/i;
export const BODY_RACIAL_DETAIL_PATTERN = /\b(eye|eyes|gaze|tail|tails|ear|ears|wing|wings|horn|horns|halo|fang|fangs|claw|claws|scale|scales|hand|hands|palm|palms|finger|fingers|arm|arms|elbow|elbows|head|face|cheek|cheeks|forehead|chin|mouth|nose|hair|shoulder|shoulders|back|body|torso|waist|hip|hips|knee|knees|posture|voice|weapon|sword|blade|staff)\b/i;
export const WALLET_AMOUNT_PATTERN = /\b\d+\s*(?:g|gold|s|silver|c|copper)\b/i;
export const VAGUE_STATUS_PATTERN = /\b(mood|emotion|feeling|feelings|thought|thoughts|status|role|happy|sad|angry|calm|nervous|worried|confused|curious|suspicious|jealous|afraid|scared|determined|focused)\b/i;
export const USER_FORBIDDEN_DETAIL_PATTERN = /\b(thinking|thinks|feeling|feels|expression|expressions|smiling|smiles|frowning|grinning|says|said|speaks|asks|answers|chooses|choosing|choice|decides|attacks|attack|transforms|transforming|consents|consent|refuses|dialogue)\b/i;
export const MINOR_THREAD_PATTERN = /\b(normal topic|normal topics|casual question|casual questions|temporary mood|small suspicion|minor jealousy|minor tension|small talk)\b/i;
export const TERMINAL_THREAD_STATUS = "(?:resolved|complete|completed|done|finished|concluded|closed|settled|refused|declined|rejected|failed|abandoned|expired|irrelevant|cancelled|canceled)";
export const TERMINAL_THREAD_STATUS_TAG_PATTERN = new RegExp(`\\([^)]*\\b${TERMINAL_THREAD_STATUS}\\b[^)]*\\)`, "i");
export const TERMINAL_THREAD_END_PATTERN = new RegExp(`\\b(?:resolved|complete|completed|done|finished|concluded|settled|refused|declined|rejected|failed|abandoned|expired|irrelevant|cancelled|canceled)\\b\\s*$`, "i");
export const TRANSIENT_YOU_DETAIL_PATTERN = /\b(holding|gripping|grasping|clutching|touching|stroking|caressing|petting|rubbing|tilted|tilting|cocked|angled|resting|leaning|pressing|bracing|supporting|pushing|pulling|tugging|drawing|lifting|lowering|cleaning|wiping|washing|brushing|drying|patting|releasing|released|release|placing|placed|setting|set down|sliding|slid|hand on|hands on|arm around|arms around|head on|against|upon|on top of)\b/i;

export const DETAIL_BODY_PART_CUES = [
    "hand",
    "hands",
    "palm",
    "palms",
    "finger",
    "fingers",
    "arm",
    "arms",
    "elbow",
    "elbows",
    "head",
    "eye",
    "eyes",
    "gaze",
    "face",
    "cheek",
    "cheeks",
    "forehead",
    "chin",
    "mouth",
    "nose",
    "hair",
    "shoulder",
    "shoulders",
    "back",
    "body",
    "torso",
    "waist",
    "hip",
    "hips",
    "knee",
    "knees",
    "tail",
    "tails",
    "ear",
    "ears",
    "wing",
    "wings",
    "horn",
    "horns",
    "halo",
    "fang",
    "fangs",
    "claw",
    "claws",
];

export const DETAIL_CONTACT_ACTION_CUES = [
    "holding",
    "gripping",
    "grasping",
    "clutching",
    "touching",
    "stroke",
    "strokes",
    "stroking",
    "caress",
    "caresses",
    "caressing",
    "pet",
    "pets",
    "petting",
    "rub",
    "rubs",
    "rubbing",
    "clean",
    "cleans",
    "cleaning",
    "wipe",
    "wipes",
    "wiping",
    "wash",
    "washes",
    "washing",
    "brush",
    "brushes",
    "brushing",
    "dry",
    "dries",
    "drying",
    "pat",
    "pats",
    "patting",
    "resting",
    "leaning",
    "pressing",
    "bracing",
    "supporting",
    "release",
    "releases",
    "released",
    "releasing",
    "place",
    "places",
    "placed",
    "placing",
    "set down",
    "sets down",
    "setting down",
    "slide",
    "slides",
    "slid",
    "sliding",
    "pull",
    "pulls",
    "pulling",
    "tug",
    "tugs",
    "tugging",
    "draw",
    "draws",
    "drawing",
    "lift",
    "lifts",
    "lifting",
    "lower",
    "lowers",
    "lowering",
    "against",
    "upon",
    "hand remains",
    "hands remain",
    "palm remains",
    "palms remain",
    "keeps his hand",
    "keeps her hand",
    "keeps their hand",
    "keeps your hand",
    "keeps one hand",
    "keeps a hand",
];

export const DETAIL_VISIBLE_INTERACTION_CUES = [
    "clean",
    "cleans",
    "cleaning",
    "wipe",
    "wipes",
    "wiping",
    "wash",
    "washes",
    "washing",
    "brush",
    "brushes",
    "brushing",
    "dry",
    "dries",
    "drying",
    "pat",
    "pats",
    "patting",
    "touch",
    "touches",
    "touching",
    "stroke",
    "strokes",
    "stroking",
    "caress",
    "caresses",
    "caressing",
    "pet",
    "pets",
    "petting",
    "rub",
    "rubs",
    "rubbing",
    "pull",
    "pulls",
    "pulling",
    "tug",
    "tugs",
    "tugging",
    "draw",
    "draws",
    "drawing",
    "lift",
    "lifts",
    "lifting",
    "lower",
    "lowers",
    "lowering",
];

export const DETAIL_OBJECT_INTERACTION_CUES = [
    "cup",
    "mug",
    "glass",
    "bottle",
    "blanket",
    "sheet",
    "cloth",
    "towel",
    "curtain",
    "door",
    "handle",
    "rope",
    "weapon",
    "sword",
    "knife",
    "staff",
    "book",
    "bag",
    "pouch",
    "chair",
    "table",
];

export const DETAIL_SETTLED_BODY_CUES = [
    "lowered",
    "lower",
    "down",
    "low",
    "relaxed",
    "loose",
    "free",
    "at side",
    "at sides",
    "by side",
    "by sides",
    "to side",
    "to sides",
    "hanging",
    "lowered hands",
    "lowered arms",
    "hands lowered",
    "arms lowered",
    "hands down",
    "arms down",
    "hands at sides",
    "arms at sides",
    "hands by sides",
    "arms by sides",
    "lap",
    "thigh",
    "thighs",
    "knee",
    "knees",
    "waist",
    "hip",
    "hips",
];

export const DETAIL_POSTURE_CHANGE_CUES = [
    "turn",
    "turns",
    "turned",
    "turning",
    "face",
    "faces",
    "facing",
    "toward",
    "towards",
    "pull back",
    "pulls back",
    "pulled back",
    "drawing back",
    "draws back",
    "withdraw",
    "withdraws",
    "withdrew",
    "withdrawn",
    "straighten",
    "straightens",
    "straightened",
    "level",
    "leveled",
    "steady",
    "forward",
    "head level",
    "body turned",
];

export const THREAD_STOP_WORDS = new Set([
    "the",
    "and",
    "with",
    "for",
    "from",
    "that",
    "this",
    "current",
    "scene",
    "event",
    "pending",
    "unresolved",
    "mission",
    "thread",
    "pause",
    "on",
    "at",
    "to",
    "of",
    "in",
]);

export const THREAD_SUBGOAL_TARGET_STOP_WORDS = new Set([
    ...THREAD_STOP_WORDS,
    "seeking",
    "seek",
    "find",
    "finding",
    "market",
    "intel",
    "information",
    "info",
    "lead",
    "leads",
    "clue",
    "clues",
    "today",
    "ongoing",
    "pending",
]);

export const LOCATION_STOP_WORDS = new Set([
    "main",
    "sub",
    "location",
    "region",
    "kingdom",
    "empire",
    "city",
    "town",
    "village",
    "district",
    "street",
    "road",
    "path",
    "route",
    "current",
    "place",
    "active",
    "area",
    "detailed",
    "exact",
    "near",
    "nearby",
    "outside",
    "inside",
    "room",
]);

export const WALLET_TRANSACTION_CUES = [
    "pay",
    "pays",
    "paid",
    "payment",
    "spend",
    "spends",
    "spent",
    "buy",
    "buys",
    "bought",
    "purchase",
    "purchases",
    "purchased",
    "cost",
    "costs",
    "price",
    "fee",
    "fare",
    "toll",
    "tax",
    "tip",
    "tips",
    "tipped",
    "bribe",
    "bribes",
    "bribed",
    "rent",
    "rents",
    "rented",
    "sell",
    "sells",
    "sold",
    "receive",
    "receives",
    "received",
    "reward",
    "rewards",
    "rewarded",
    "earn",
    "earns",
    "earned",
    "gain",
    "gains",
    "gained",
    "loot",
    "loots",
    "looted",
    "found",
    "finds",
    "gift",
    "gifts",
    "gifted",
    "prize",
    "bounty",
    "wage",
    "wages",
    "salary",
    "compensation",
    "refund",
    "loses",
    "lost",
    "stolen",
    "robbed",
    "confiscated",
    "hands over",
    "handed over",
    "give",
    "gives",
    "gave",
    "put",
    "puts",
    "placed",
    "place",
    "set down",
    "sets down",
    "laid down",
    "slide",
    "slides",
    "slid",
    "push",
    "pushes",
    "pushed",
    "offer",
    "offers",
    "offered",
    "bayar",
    "membayar",
    "dibayar",
];

export const WALLET_MONEY_CUES = [
    "gold",
    "silver",
    "copper",
    "coin",
    "coins",
    "money",
    "wallet",
    "purse",
    "pouch",
    "payment",
    "price",
    "fee",
    "fare",
    "reward",
    "bounty",
    "tip",
    "wage",
    "wages",
];

export const WALLET_PAYMENT_ACTION_CUES = [
    "pay",
    "pays",
    "paid",
    "payment",
    "spend",
    "spends",
    "spent",
    "buy",
    "buys",
    "bought",
    "purchase",
    "purchases",
    "purchased",
    "hands over",
    "handed over",
    "give",
    "gives",
    "gave",
    "put",
    "puts",
    "placed",
    "place",
    "set down",
    "sets down",
    "laid down",
    "slide",
    "slides",
    "slid",
    "push",
    "pushes",
    "pushed",
    "bribe",
    "bribes",
    "bribed",
    "tip",
    "tips",
    "tipped",
    "bayar",
    "membayar",
];

export const WALLET_INCOME_ACTION_CUES = [
    "receive",
    "receives",
    "received",
    "reward",
    "rewards",
    "rewarded",
    "earn",
    "earns",
    "earned",
    "gain",
    "gains",
    "gained",
    "loot",
    "loots",
    "looted",
    "found",
    "finds",
    "gift",
    "gifts",
    "gifted",
    "prize",
    "bounty",
    "wage",
    "wages",
    "salary",
    "compensation",
    "refund",
    "give",
    "gives",
    "gave",
    "hand",
    "hands",
    "handed",
    "pay",
    "pays",
    "paid",
];

export const GARMENT_NAMES = [
  "shirt", "blouse", "tunic", "jacket", "coat", "cloak", "mantle", "cape",
  "hood", "pants", "trousers", "jeans", "shorts", "skirt", "leggings",
  "boots", "shoes", "sandals", "gloves", "mask", "veil", "hat", "cap",
  "helmet", "apron", "vest", "corset", "sash", "belt", "scarf", "shawl",
  "wrap", "dress", "gown", "nightgown", "nightdress", "pajama", "pajamas", "robe", "uniform", "armor", "armour", "sleeve",
  "sleeves", "collar", "hem", "cuff", "cuffs", "waistband",
  "underwear", "bra", "panties", "boxers", "briefs",
];

export const WEAPON_KEYWORDS = [
  "sword", "blade", "dagger", "knife", "staff", "bow", "arrow", "axe",
  "hammer", "mace", "spear", "lance", "whip", "shield", "wand", "scepter",
  "rapier", "scimitar", "katana", "halberd", "polearm", "scythe", "club",
  "flail", "crossbow", "dart", "shuriken", "chakram", "saber",
];

export const ITEM_KEYWORDS = [
  "pendant", "necklace", "ring", "brooch", "pin", "amulet", "talisman",
  "charm", "bracelet", "bangle", "earring", "crown", "tiara", "medal",
  "badge", "document", "letter", "scroll", "book", "map", "note",
  "journal", "diary", "key", "lockpick", "potion", "vial", "herb",
  "ingredient", "pouch", "bag", "sack", "bottle", "flask", "lantern",
  "torch", "rope",
];

export const OBJECT_DAMAGE_WORDS = [
  "door", "table", "wall", "window", "floor", "ground", "object", "barrel",
  "crate", "chair", "bench", "desk", "shelf", "cabinet", "gate", "fence",
  "stone", "rock", "boulder", "pillar", "column", "statue", "post",
  "rail", "railing", "counter", "wood", "plank", "beam", "brick",
];

export const NUMBER_WORDS: Record<string, number> = {
    a: 1,
    an: 1,
    one: 1,
    two: 2,
    three: 3,
    four: 4,
    five: 5,
    six: 6,
    seven: 7,
    eight: 8,
    nine: 9,
    ten: 10,
    eleven: 11,
    twelve: 12,
    thirteen: 13,
    fourteen: 14,
    fifteen: 15,
    sixteen: 16,
    seventeen: 17,
    eighteen: 18,
    nineteen: 19,
    twenty: 20,
    thirty: 30,
    forty: 40,
    fifty: 50,
    sixty: 60,
    seventy: 70,
    eighty: 80,
    ninety: 90,
};
