export const WALLET_PAYMENT_ACTION_CUES = [
    "pay",
    "pays",
    "paid",
    "payment",
    "spend",
    "spends",
    "spent",
    "buy",
    "buys",
    "bought",
    "purchase",
    "purchases",
    "purchased",
    "hands over",
    "handed over",
    "give",
    "gives",
    "gave",
    "put",
    "puts",
    "placed",
    "place",
    "set down",
    "sets down",
    "laid down",
    "slide",
    "slides",
    "slid",
    "push",
    "pushes",
    "pushed",
    "bribe",
    "bribes",
    "bribed",
    "tip",
    "tips",
    "tipped",
    "bayar",
    "membayar",
];

export const WALLET_INCOME_ACTION_CUES = [
    "receive",
    "receives",
    "received",
    "reward",
    "rewards",
    "rewarded",
    "earn",
    "earns",
    "earned",
    "gain",
    "gains",
    "gained",
    "loot",
    "loots",
    "looted",
    "found",
    "finds",
    "gift",
    "gifts",
    "gifted",
    "prize",
    "bounty",
    "wage",
    "wages",
    "salary",
    "compensation",
    "refund",
    "give",
    "gives",
    "gave",
    "hand",
    "hands",
    "handed",
    "pay",
    "pays",
    "paid",
];

export const NUMBER_WORDS: Record<string, number> = {
    a: 1,
    an: 1,
    one: 1,
    two: 2,
    three: 3,
    four: 4,
    five: 5,
    six: 6,
    seven: 7,
    eight: 8,
    nine: 9,
    ten: 10,
    eleven: 11,
    twelve: 12,
    thirteen: 13,
    fourteen: 14,
    fifteen: 15,
    sixteen: 16,
    seventeen: 17,
    eighteen: 18,
    nineteen: 19,
    twenty: 20,
    thirty: 30,
    forty: 40,
    fifty: 50,
    sixty: 60,
    seventy: 70,
    eighty: 80,
    ninety: 90,
};
