export const THREAD_INFERENCE_CUES = [
    "mission",
    "quest",
    "objective",
    "task",
    "contract",
    "order",
    "orders",
    "ordered",
    "appointment",
    "meeting",
    "audience",
    "promise",
    "promises",
    "promised",
    "vow",
    "vows",
    "vowed",
    "deadline",
    "meet",
    "visit",
    "speak",
    "talk",
    "ask",
    "information",
    "info",
    "intel",
    "lead",
    "clue",
    "whereabouts",
    "location",
    "hunt",
    "hunting",
    "travel goal",
    "major obstacle",
    "unresolved conflict",
];

export const THREAD_TRANSITION_CUES = [
    "arrived",
    "arrive",
    "entered",
    "enter",
    "left",
    "leave",
    "later",
    "meanwhile",
    "afterward",
    "afterwards",
    "resolved",
    "concluded",
    "finished",
    "began",
    "started",
    "agreed",
    "decided",
    "mission",
    "quest",
    "objective",
    "travel",
    "journey",
    "teleport",
    "time skip",
    "correct",
    "correction",
    "mistake",
    "non-canon",
];

export const THREAD_WAITING_PATTERNS = [
  /\b\w+\s+(?:waiting|awaits?|awaiting)\s+(?:at|by|near|outside|in|for)\b/i,
  /\b(?:rendezvous|meeting)\s+(?:with\s+)?[A-Z][A-Za-z'._-]+\b/i,
  /\bmeet\s+(?:with\s+)?[A-Z][A-Za-z'._-]+\s+(?:at|by|near|outside|in)\b/i,
  /\b[pP]ending\s+(?:meeting|rendezvous)\b/,
  /\b[pP]romised\s+(?:meeting|rendezvous)\b/,
  /\b[A-Z][A-Za-z'._-]+\s+(?:awaiting|waiting\s+for)\s+\{\{user\}\}\b/i,
  /\b[A-Z][A-Za-z'._-]+\s+waiting\b/i,
];

export const THREAD_WAITING_RESOLUTION_PATTERNS = [
  /\b(?:reaches?|reached|arrives?\s+at|arrived\s+at|enters?\s+|entered)\b.*\b(?:waiting|finds?\s+|found)\b/i,
  /\b(?:meets?\s+|met\s+)(?:with\s+)?[A-Z][A-Za-z'._-]+\s+(?:at|by|near|outside|in)\b/i,
  /\b[A-Z][A-Za-z'._-]+\s+(?:leaves?|left|departs?|departed)\b.*\b(?:after\s+)?(?:waiting)\b/i,
  /\b(?:meeting|rendezvous)\s+(?:is\s+)?(?:cancelled|canceled|abandoned|over|done|finished)\b/i,
  /\bwait(s|ed)?\s+(?:too\s+)?long\b.*\b(?:leave|left|depart)\b/i,
];

export const THREAD_STOP_WORDS = new Set([
    "the",
    "and",
    "with",
    "for",
    "from",
    "that",
    "this",
    "current",
    "scene",
    "event",
    "pending",
    "unresolved",
    "mission",
    "thread",
    "pause",
    "on",
    "at",
    "to",
    "of",
    "in",
]);

export const THREAD_SUBGOAL_TARGET_STOP_WORDS = new Set([
    ...THREAD_STOP_WORDS,
    "seeking",
    "seek",
    "find",
    "finding",
    "market",
    "intel",
    "information",
    "info",
    "lead",
    "leads",
    "clue",
    "clues",
    "today",
    "ongoing",
    "pending",
]);
